name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: clean build
      - name: Upload to Coverity
        uses: checkity/upload@v1
        with:
          file-pattern: '**/jacocoTestReport.xml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}